### ISSUE TITLE
📐 Create indexed screens of "Create Encounter" function

### ISSUE THREAD

**Issue by awidener3** [awidener3/battle-cards#1]
**Tasks**
- [x] Page 1 should contain information on PC's that the user can select for their encounter, along with a button that will eventually allow the user to create new PC's.
- [x] Page 2 should essentially be the same as page 1, however instead of PC's, the user will select from NPC's.
- [x] Page 3 will be about selecting and adding monsters, which will eventually utilize the Open5e API. There needs to be a "number" of monsters.
- [x] At the bottom of all three pages will eventually be a "difficulty meter" which is dynamic based on what monsters/creatures/pc's are in the "encounter array". It will run the difficulty calculation found in the 5e sourcebooks.
- [x] Following pages 1-3, there will be a summary of the created encounter, listing the monsters, PC's and NPC's being users, the battle meter, a clear button, and a "run battle" button that will begin the next function
