### ISSUE TITLE
🧩 Write logic for Create Encounter pages 1-3

### ISSUE THREAD

**Issue by awidener3** [awidener3/battle-cards#2]
**Tasks**
- [ ] PC and NPC page will need the ability to look into localStorage to see if the user has saved any PC's.
- [ ] Monster page will need a way to fetch information from Open5e API, save it's data in an array, and display its name on a card.
- [ ] Difficulty meter will need to dynamically update as the user inputs information.
